FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY . .
RUN mvn -pl api-gateway/ecoquest-api-gateway -am package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/api-gateway/ecoquest-api-gateway/target/*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
