package com.ecoquest.report;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

@Service
class ReportExportService {
    private static final Color GREEN = new Color(28, 124, 84);
    private static final Color LIGHT_GREEN = new Color(233, 246, 239);
    private static final Color DARK = new Color(24, 39, 31);
    private static final Color MUTED = new Color(91, 111, 99);
    private static final DateTimeFormatter DATE =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm", Locale.ENGLISH).withZone(ZoneId.systemDefault());

    byte[] analyticsPdf(AnalyticsSummary summary) {
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            Document document = new Document(PageSize.A4, 36, 36, 34, 34);
            PdfWriter.getInstance(document, out);
            document.open();

            Font title = new Font(Font.HELVETICA, 20, Font.BOLD, GREEN);
            Font subtitle = new Font(Font.HELVETICA, 10, Font.NORMAL, MUTED);
            Font section = new Font(Font.HELVETICA, 13, Font.BOLD, DARK);
            Font body = new Font(Font.HELVETICA, 10, Font.NORMAL, DARK);
            Font small = new Font(Font.HELVETICA, 8, Font.NORMAL, MUTED);

            Paragraph heading = new Paragraph("EcoQuest Campus Analytics Report", title);
            heading.setAlignment(Element.ALIGN_CENTER);
            document.add(heading);
            Paragraph meta = new Paragraph(
                    "Period: " + summary.period().toUpperCase(Locale.ENGLISH)
                            + " | From " + DATE.format(summary.from())
                            + " to " + DATE.format(summary.to()),
                    subtitle);
            meta.setAlignment(Element.ALIGN_CENTER);
            meta.setSpacingAfter(18);
            document.add(meta);

            addSection(document, "Executive Summary", section);
            PdfPTable metrics = new PdfPTable(3);
            metrics.setWidthPercentage(100);
            metrics.setSpacingAfter(14);
            metric(metrics, "Submitted actions", summary.submittedActions(), body);
            metric(metrics, "Accepted actions", summary.acceptedActions(), body);
            metric(metrics, "Rejected actions", summary.rejectedActions(), body);
            metric(metrics, "Points granted", summary.totalPoints(), body);
            metric(metrics, "Missions created", summary.missionsCreated(), body);
            metric(metrics, "Users registered", summary.usersRegistered(), body);
            metric(metrics, "Open reports", summary.openReports(), body);
            metric(metrics, "Accepted reports", summary.acceptedReports(), body);
            metric(metrics, "Rejected reports", summary.rejectedReports(), body);
            metric(metrics, "Badges granted", summary.badgesGranted(), body);
            metric(metrics, "Certificates issued", summary.certificatesIssued(), body);
            metric(metrics, "Top students tracked", summary.topStudents().size(), body);
            document.add(metrics);

            addSection(document, "Action Types", section);
            PdfPTable actionTypes = new PdfPTable(new float[]{3f, 1.4f, 1.4f});
            actionTypes.setWidthPercentage(100);
            header(actionTypes, "Action type", "Accepted actions", "Points");
            summary.actionTypes().forEach(row -> {
                cell(actionTypes, row.actionType(), body);
                cell(actionTypes, row.actionCount(), body);
                cell(actionTypes, row.points(), body);
            });
            document.add(actionTypes);

            addSection(document, "Top Students", section);
            PdfPTable students = new PdfPTable(new float[]{2.2f, 1.4f, 1.4f});
            students.setWidthPercentage(100);
            header(students, "Student ID", "Accepted actions", "Points");
            summary.topStudents().stream().limit(15).forEach(row -> {
                cell(students, row.studentId(), body);
                cell(students, row.actionCount(), body);
                cell(students, row.points(), body);
            });
            document.add(students);

            Paragraph footer = new Paragraph(
                    "Generated by Report Service read model. Source events: actions, rewards, badges, certificates, missions, users and reports.",
                    small);
            footer.setSpacingBefore(18);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);
            document.close();
            return out.toByteArray();
        } catch (Exception ex) {
            throw new IllegalStateException("Could not export analytics report PDF.", ex);
        }
    }

    byte[] analyticsSeriesPdf(AnalyticsSeries series) {
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            Document document = new Document(PageSize.A4.rotate(), 28, 28, 28, 28);
            PdfWriter.getInstance(document, out);
            document.open();

            Font title = new Font(Font.HELVETICA, 19, Font.BOLD, GREEN);
            Font subtitle = new Font(Font.HELVETICA, 10, Font.NORMAL, MUTED);
            Font section = new Font(Font.HELVETICA, 12, Font.BOLD, DARK);
            Font body = new Font(Font.HELVETICA, 8, Font.NORMAL, DARK);
            Font small = new Font(Font.HELVETICA, 7, Font.NORMAL, MUTED);

            Paragraph heading = new Paragraph("EcoQuest Campus Analytics Series", title);
            heading.setAlignment(Element.ALIGN_CENTER);
            document.add(heading);
            Paragraph meta = new Paragraph("Scope: " + series.period().toUpperCase(Locale.ENGLISH)
                    + " | Buckets: " + series.buckets().size(), subtitle);
            meta.setAlignment(Element.ALIGN_CENTER);
            meta.setSpacingAfter(14);
            document.add(meta);

            addSection(document, "Period-by-period system report", section);
            PdfPTable table = new PdfPTable(new float[]{1.35f, 1.2f, 1.2f, 1.2f, 1.25f, 1.1f, 1.1f, 1.1f, 1.1f, 1.2f});
            table.setWidthPercentage(100);
            header(table, "Period", "Actions", "Accepted", "Rejected", "Points", "Missions", "Users", "Badges", "Certs", "Open reports");
            series.buckets().forEach(row -> {
                cell(table, row.label(), body);
                cell(table, row.submittedActions(), body);
                cell(table, row.acceptedActions(), body);
                cell(table, row.rejectedActions(), body);
                cell(table, row.totalPoints(), body);
                cell(table, row.missionsCreated(), body);
                cell(table, row.usersRegistered(), body);
                cell(table, row.badgesGranted(), body);
                cell(table, row.certificatesIssued(), body);
                cell(table, row.openReports(), body);
            });
            document.add(table);

            Paragraph footer = new Paragraph(
                    "Generated by Report Service read model. Weekly exports include every ISO week intersecting the selected year; monthly exports include all twelve months; yearly exports include each year in the selected range.",
                    small);
            footer.setSpacingBefore(14);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);
            document.close();
            return out.toByteArray();
        } catch (Exception ex) {
            throw new IllegalStateException("Could not export analytics series PDF.", ex);
        }
    }

    private void addSection(Document document, String label, Font font) throws Exception {
        Paragraph paragraph = new Paragraph(label, font);
        paragraph.setSpacingBefore(10);
        paragraph.setSpacingAfter(8);
        document.add(paragraph);
    }

    private void metric(PdfPTable table, String label, long value, Font font) {
        PdfPCell cell = new PdfPCell();
        cell.setPadding(10);
        cell.setBorderColor(new Color(207, 226, 217));
        cell.setBackgroundColor(LIGHT_GREEN);
        cell.addElement(new Paragraph(label, new Font(Font.HELVETICA, 8, Font.NORMAL, MUTED)));
        cell.addElement(new Paragraph(String.format(Locale.ENGLISH, "%,d", value),
                new Font(Font.HELVETICA, 16, Font.BOLD, GREEN)));
        table.addCell(cell);
    }

    private void header(PdfPTable table, String... labels) {
        for (String label : labels) {
            PdfPCell cell = new PdfPCell(new Phrase(label, new Font(Font.HELVETICA, 9, Font.BOLD, Color.WHITE)));
            cell.setBackgroundColor(GREEN);
            cell.setBorder(Rectangle.NO_BORDER);
            cell.setPadding(7);
            table.addCell(cell);
        }
    }

    private void cell(PdfPTable table, Object value, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(String.valueOf(value), font));
        cell.setPadding(7);
        cell.setBorderColor(new Color(226, 232, 228));
        table.addCell(cell);
    }
}
