server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  client_max_body_size 100m;
  resolver 127.0.0.11 valid=5s ipv6=off;

  location / {
    try_files $uri /index.html;
  }

  location /policies/ {
    set $policy_backend verification-policy-grpc-service:8090;
    proxy_pass http://$policy_backend$request_uri;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location ~ ^/(auth|catalog|actions|rewards|leaderboards|recognitions|reports|notifications)(/|$) {
    set $api_backend api-gateway:8080;
    proxy_pass http://$api_backend$request_uri;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 1h;
    proxy_send_timeout 1h;
  }
}
